### ISSUE TITLE
Sudo commands unsecure to whitelist

### ISSUE THREAD

**Issue by micred** [platanus/capistrano3-nginx#14]
Hi, how is sudo is meant to be configured?
I don't want to give all sudo access to the user deploy, so I whitelist only some commands.
Tasks nginx:site:add / enable / disable / remove don't have not absolute paths so they can't be whitelisted effectively.

**Comment by blackjid** [comment]
I'm going to close, this issue.
I think you were on the right track.

Please feel free to reopen it if you see need.
