### ISSUE TITLE
sudo: /etc/init.d/nginx: command not found

### ISSUE THREAD

**Issue by dsylla** [platanus/capistrano3-nginx#17]
i'm having trouble using this gem.

I'm connecting to a vagrant ubuntu-14-04 with nginx and rbenv and i got stuck with this error which I really don't understand.

```
{15-01-28 19:23}[2.1.2]***-iMac:~/Sites/***@feature/capistrano✗✗✗✗✗✗ david% cap staging nginx:reload
DEBUG [36de0c74] Running /usr/bin/env [ -d ~/.rbenv/versions/2.1.5 ] as vagrant@**.vagrant.dev
DEBUG [36de0c74] Command: [ -d ~/.rbenv/versions/2.1.5 ]
DEBUG [36de0c74] Finished in 0.163 seconds with exit status 0 (successful).
DEBUG [426d8b6c] Running /usr/bin/env [ $(sudo /etc/init.d/nginx configtest | grep -c 'fail') -eq 0 ] as vagrant@***.vagrant.dev
DEBUG [426d8b6c] Command: [ $(sudo /etc/init.d/nginx configtest | grep -c 'fail') -eq 0 ]
DEBUG [426d8b6c]        sudo: /etc/init.d/nginx: command not found
DEBUG [426d8b6c]        
DEBUG [426d8b6c] Finished in 0.006 seconds with exit status 0 (successful).
INFO [0b2fdc5b] Running /usr/bin/env sudo /etc/init.d/nginx reload as vagrant@***.vagrant.dev
DEBUG [0b2fdc5b] Command: ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.1.5 /usr/bin/env sudo /etc/init.d/nginx reload )
DEBUG [0b2fdc5b]        sudo: /etc/init.d/nginx: command not found
DEBUG [0b2fdc5b]       
``` 

When I try this with vagrant ssh everything works fine.

```
vagrant@vagrant-ubuntu-trusty-64:~$ /usr/bin/env sudo service nginx reload
 * Reloading nginx configuration nginx
```

Please help :)

**Comment by blackjid** [comment]
for some reason is trying to use `/etc/init.d/nginx` to restart de service, the default behaviour should be to use `service nginx`

are you explicitly setting the `set :nginx_service_path, "/etc/init.d/nginx"` variable? If you are doing it, that's why... try removing that line...

**Comment by blackjid** [comment]
any luck with this?

**Comment by blackjid** [comment]
@dsylla did you work this out?
I'm going to close it, but if you still have problems, and you want to continue the discussion please feel free to reopen the issue.

**Comment by kaleemullah360** [comment]
**Here is workout for this issue:**
[https://github.com/capistrano-plugins/capistrano-unicorn-nginx/compare/master...erwald:38f9e9c](https://github.com/capistrano-plugins/capistrano-unicorn-nginx/compare/master...erwald:38f9e9c)

I followed instructions and got success. unless gem space is not altered.
