### ISSUE TITLE
Support for http and https simultaneously 

### ISSUE THREAD

**Issue by bilby91** [platanus/capistrano3-nginx#23]
Is there any interest in supporting this ?

**Comment by blackjid** [comment]
you should be able to do this passing your own nginx template thought the `nginx_template`, although, I haven't had the need for this

**Comment by blackjid** [comment]
you don't want to redirect the `http` to `https` right??

**Comment by bilby91** [comment]
@blackjid we want to support multiple protocols at the same time. Some client where having some specific issue with https.

**Comment by blackjid** [comment]
did the custom template throught `nginx_template` solve your problem???
I think is a very specific case to add it the default template...

**Comment by bilby91** [comment]
Yes. Maybe you can close this. Too specific. Thanks for the help!

**Comment by blackjid** [comment]
thanks!
