### ISSUE TITLE
nginx:site:disable doesn't work correctly when custom :nginx_application_name is set

### ISSUE THREAD

**Issue by ssnepenthe** [platanus/capistrano3-nginx#26]
Thanks for the great tool! I have just started using capistrano and this has been very helpful, with one small issue.

it looks like `add`, `enable` and `remove` all use `:nginx_application_name` (directly or indirectly) to determine the name for a site config file. however, `disable` uses `:application`.

so if i set `:application` to `mysite.com` and `:nginx_application_name` to `#{fetch(:application)}.conf` i see the following behavior:

`nginx:site:add` -> creates `mysite.com.conf` in sites-available.

`nginx:site:enable` -> links `mysite.com.conf` to sites-enabled.

`nginx:site:remove` -> removes `mysite.com.conf` from sites-available.

so far, so good. but:

`nginx:site:disable` -> attempts to remove `mysite.com` from sites-enabled, reports success, but hasn't actually done anything.

**Comment by blackjid** [comment]
you are right... good catch,... I don't usually use the disable task...
https://github.com/platanus/capistrano3-nginx/blob/master/lib/capistrano/tasks/nginx.rake#L136
is using `:application` and it should use `:enabled_application`

I'll try to fix it tonight...

**Comment by blackjid** [comment]
fixed on https://github.com/platanus/capistrano3-nginx/commit/c249985a3c96d62c34f2493b60590dd4110c0594
