### ISSUE TITLE
Question. How to use inside deploy.rb

### ISSUE THREAD

**Issue by jorgeorpinel** [platanus/capistrano3-nginx#27]
Hi,

I'm not a ruby expert... Do you know if there's a way to use these tasks inside my own deploy task? (without running a separate `cap` command) For example how can I use nginx:site:add after deploy:finished ? Any direction is appreciated.

Thanks!

**Comment by blackjid** [comment]
that is not ruby specific, is capistrano, you should read their documentation.

Here is a link where they explain the before and after hooks that you could use for your use case
http://capistranorb.com/documentation/getting-started/before-after/#

**Comment by jorgeorpinel** [comment]
OK thanks, the `invoke` function sounds like my best bet.

**Comment by jorgeorpinel** [comment]
One more question though: do you happen to know how to only invoke a task on the very first deployment? ..or if the nginx config file doesn't exist in the server for some reason? ...or if the nginx config temlplate changed... OK might as well add/enable/reload each time... d:

**Comment by blackjid** [comment]
capistrano v2 used to have a `deploy:cold` task that was used for first time tasks... buen they removed in capistrano v3.... Now the idea es that all tasks should be idempotent... 
So this nginx extention will just update the nginx conf every time... and reload nginx after that.

Also in here https://github.com/platanus/negroku/blob/master/lib/negroku/capistrano/tasks/thinking_sphinx.rake i'm cheking if sphinx configuration has changed or not and based on that I the script reset the indexes or not.

I hope it helps
