### ISSUE TITLE
it won't use my ssl certs options when I deploy

### ISSUE THREAD

**Issue by jfabre** [platanus/capistrano3-nginx#31]
I get an nginx config error after deploy with ssl turned on.

set :nginx_use_ssl, true seems to work because I can see it in the deployed config file

but

set :nginx_ssl_certificate_path, "foo"
set :nginx_ssl_certificate_key_path, "bar"
set :nginx_ssl_certificate, "foo"
set :nginx_ssl_certificate_key, "bar"

always use the default values even though I've specified the values in deploy.rb.
I don't get it, the code in your gem template is pretty straightforward.
I'm about to just create symbolic links on my server to make this work.

Any idea on why this could occur?

**Comment by jfabre** [comment]
Ok I figured out why... 
I'm using capistrano-puma that has an nginx part and I confused the two.
The nginx part was overwriting your configuration...

**Comment by blackjid** [comment]
👍  thanks for clarifying!
