### ISSUE TITLE
cap nginx:site:add is missing a destination for 'mv' command

### ISSUE THREAD

**Issue by jawad-shuja** [platanus/capistrano3-nginx#36]
https://github.com/platanus/capistrano3-nginx/blob/ccf63acf2c4a19af2adeb01a4ac811b0c40e30f2/lib/capistrano/tasks/nginx.rake#L112

Hello,

In my application, the command `bundle exec cap staging nginx:site:add` is executing `sudo mv /tmp/nginx.conf` without any destination. This leads to the following error:

> missing destination file operand after '/tmp/nginx.conf'

The argument list in the task appends `fetch(:nginx_application_name)` to the `mv` command. Should it not be `fetch(:available_application)` which gives the destination path? Or am I missing something here?

**Comment by blackjid** [comment]
Hi,

If you see the complete task definition, it has a `within` method, that means that all commands in the block will be executed in the context of the directory passed to `within` as an argument.

https://github.com/platanus/capistrano3-nginx/blob/ccf63acf2c4a19af2adeb01a4ac811b0c40e30f2/lib/capistrano/tasks/nginx.rake#L103-L115

Is like doing `cd #{fetch(:sites_available)}` and `:sites_available` defaults to `nginx_sites_available_dir`

https://github.com/platanus/capistrano3-nginx/blob/ccf63acf2c4a19af2adeb01a4ac811b0c40e30f2/lib/capistrano/tasks/nginx.rake#L45

I'm not really sure what's happening and I'm not using capistrano anymore, so is difficult for me to test anything out...

**Comment by jawad-shuja** [comment]
@blackjid thanks for the clarification! I am now using the `puma:nginx_config` task provided by the capistrano3-puma gem in order to upload my config. I'll look into this again later. For now I am going to close the issue.
