### ISSUE TITLE
Mantainer Wanted

### ISSUE THREAD

**Issue by blackjid** [platanus/capistrano3-nginx#37]
We are looking for a maintainer, as we are no using this gem anymore.
We are willing to transfer the repo and the rubygems access

**Comment by zakwanhaj** [comment]
Which tool do you use now to manage nginx files? sorry, I am asking because we are looking for a similar solution to handle nginx configurations in several servers.

**Comment by blackjid** [comment]
Hi, we are not using nginx anymore, but I suggest taking a look at ansible

https://www.ansible.com
https://github.com/geerlingguy/ansible-role-nginx

**Comment by treenewbee** [comment]
I will take it.

**Comment by frontandstart** [comment]
@blackjid what is replacement for nginx? apache2? or handle request directly by puma?
One year ago I start use for small projects [seuros/capistrano-puma](https://github.com/seuros/capistrano-puma)

**Comment by treenewbee** [comment]
@blackjid Sounds good, I will do it in my fork, also the rubygems.

**Comment by blackjid** [comment]
great! What's your rubygems email? You can share it here or email me at
jidonoso at gmail dot com

**Comment by blackjid** [comment]
Thanks @treenewbee I added you as owner on rubygems and edited this fork readme to lead people to yours.
